weights: ./models/st_gcn.ntu-xsub.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/dguha_dataset/dguha_pcl_ahc_test.npy
  label_path: ./data/dguha_dataset/dguha_test_label.pkl

# skeleton_test_feeder_args 
skeleton_test_feeder_args:
  data_path: ./data/dguha_dataset/dguha_sk_test.npy
  label_path: ./data/dguha_dataset/dguha_test_label.pkl

# model
model: net.mtgea.MTGEA

model_args:

  base_model: net.st_gcn.Model
  in_channels: 3
  num_class: 32
  output_class: 7
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: double_test
device: [3]
test_batch_size: 13

